name: core_example
description: This project holds information about registering a license key with Syncfusion Flutter Widgets.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^26.2.8

  cupertino_icons: '>=0.1.3 <1.0.7'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
